### ISSUE TITLE
CmdShim struct is not public

### ISSUE THREAD

**Issue by krispetkov** [cloudfoundry/goshims#6]
Hello, 
Can you please tell me the reason why cmdShim struct is private but not public?
How can I pass such a struct if I need to?

What I mean is the for example ExecShim struct is public and I can do the following:

`br := myBroker.New(logger, &osshim.OsShim{}, &execshim.ExecShim{})`

but I'm unable to pass **&execshim.cmdShim{}** because it is private.

For example: `br := myBroker.New(logger, &osshim.OsShim{}, &execshim.cmdShim{})`

**Comment by lisamburns** [comment]
Hi @KrisPetkov 

Normally you would pass the execshim object and then use execshim.Command or execshim.CommandContext to create a cmdShim object.  You can see an example of that here:
https://github.com/cloudfoundry/smb-volume-k8s-release/blob/19d1e16891e50034d5c9719790c313abd8306de5/smb-csi-driver/nodeserver/node_server.go#L150

If you just want to pass one of the shimmed out Cmd objects within your code, you can use the exec.Cmd interface directly as cmdShim is an implementation of that interface.
